### ISSUE TITLE
installing ckanext-publicamundi (ckan 2.5.1)

### ISSUE THREAD

**Issue by illoi** [PublicaMundi/ckanext-publicamundi#229]
v: ckan 2.5.1, ubuntu 14.04, apache2, python 2.7.6
by installing publicamundi I get following error:
ImportError: cannot import name toolkit

I have downloaded the zip file (source: https://github.com/PublicaMundi/ckanext-publicamundi)
and worked as follows:

'. /usr/lib/ckan/default/bin/activate'
'cd /usr/lib/ckan/default/src'

'pip install -r requirements.txt'
'python setup.py develop'
'paster publicamundi --config /etc/ckan/default/production.ini setup'

 'apt-get install libgeos-c1'

'sudo apt-get install libxml2-dev libxslt1-dev python-dev'
'sudo apt-get install python-lxml'
'pip install lxml'

by giving the command 'paster publicamundi --config /etc/ckan/default/production.ini setup'
I get **ImportError: cannot import name toolkit**
I try to import toolkit, but I get *_NameError: name 'toolkit' is not defined *_

**Comment by kalxas** [comment]
ckanext-publicamundi is not yet tested/ported to CKAN 2.5.
Our stable release is based on CKAN 2.2

**Comment by illoi** [comment]
many thanks

**Comment by jguo144** [comment]
How much effort would be required to get ckanext-publicamundi working on CKAN 2.5?

**Comment by kalxas** [comment]
Hi @jguo144 
I think it would require around 3-4 man months to do such a port, since there are many things that changed within CKAN (mostly in the 2.3 release)

**Comment by stevenvandervalk** [comment]
@kalxas Thanks for confirming this! I couldn't understand the nature of my GDAL and Geoalchemy errors.  Do you know of any efforts/ workarounds besides https://github.com/GeoinformationSystems/ckanext-geoserver that would enable publishing of CKAN datasets to a geoserver/mapserver?

**Comment by kalxas** [comment]
@stevenvandervalk I am not aware of any. Feel free to look at that part of our code.
